/** Funnel + contacts locked to the live vaasx.com product. */
export const LINKS = {
  site: "https://vaasx.com",
  docs: "https://vaasx.com/docs",
  guides: "https://vaasx.com/guides",
  whitepapers: "https://vaasx.com/whitepapers",
  mcp: "https://mcp.vaasx.com/mcp",
  registry: "io.github.VAAS-X/vaasxmcp",
  github: "https://github.com/VAAS-X/vaas-x",
  sales: "sales@vaasx.com",
  hello: "hello@vaasx.com",
  support: "support@vaasx.com",
};

/**
 * Complete marketing funnel for VAAS-X.
 * Each stage: goal, owned assets, CTA, success metric, next stage.
 */
export const FUNNEL = [
  {
    id: "awareness",
    name: "Awareness",
    goal: "Be discovered as operational memory infrastructure — not a chatbot or vector DB.",
    assets: [
      "vaasx.com homepage",
      "GitHub VAAS-X/vaas-x",
      "Official MCP registry listing (vaasxmcp)",
      "Whitepapers + guides index",
    ],
    cta: "Visit vaasx.com / view MCP listing",
    metric: "Unique site + registry views",
    next: "capture",
    channels: ["MCP registry", "GitHub", "LinkedIn", "Docs SEO", "Partner mentions"],
  },
  {
    id: "capture",
    name: "Capture",
    goal: "Issue a free API key (no card) and identify surface: SDK vs MCP.",
    assets: ["vaasx.com free key flow", "Pricing / signup", "MCP OAuth + key link"],
    cta: "Get free API key",
    metric: "Keys issued",
    next: "activation",
    channels: ["Product site CTA", "MCP connector auth", "Outreach email"],
  },
  {
    id: "activation",
    name: "Activation",
    goal: "First successful remember/ingest + recall/query on their data or a guide dataset.",
    assets: [
      "pip install vaas-x quickstart",
      "vaasxmcp recall/remember tools",
      "Reproduction guides (CMAPSS, occupancy, CartPole, …)",
    ],
    cta: "Run quickstart or connect MCP",
    metric: "Accounts with ≥1 recall after ingest",
    next: "engagement",
    channels: ["Docs", "Guides", "In-product empty states", "Sales-assisted setup"],
  },
  {
    id: "engagement",
    name: "Engagement",
    goal: "Compound usage across sessions/devices; prove outcome-weighted recall on their domain.",
    assets: [
      "Docs developer guide",
      "Whitepapers by vertical",
      "Multi-device / HiveMind messaging",
      "hello@ / support@ help",
    ],
    cta: "Complete a guide or request a working session",
    metric: "Weekly active recalling accounts",
    next: "conversion",
    channels: ["Email nurture", "Docs", "Demo calls"],
  },
  {
    id: "conversion",
    name: "Conversion",
    goal: "Upgrade Free → Developer (£19/mo) or Professional (£99/mo) when limits bind.",
    assets: ["Pricing page", "Limit-wall upgrade UX", "Tier talk-tracks"],
    cta: "Upgrade plan",
    metric: "Paid conversions / MRR",
    next: "expansion",
    channels: ["In-app limit wall", "sales@ outbound to warm keys"],
  },
  {
    id: "expansion",
    name: "Expansion",
    goal: "Enterprise: on-prem, air-gap, federation, compliance-sensitive deployments.",
    assets: ["Enterprise conversations", "NDA whitepapers", "sales@vaasx.com"],
    cta: "Talk to sales / pilot deployment",
    metric: "Enterprise pipeline + closed-won",
    next: null,
    channels: ["Direct sales", "Partner intros", "Event follow-up"],
  },
];

/**
 * Potential contacts / lead targets.
 * Only public org emails and public URLs — no invented personal inboxes.
 * status: public-channel | persona-target | owned | ecosystem
 */
export const CONTACTS = [
  // Owned
  {
    id: "owned-sales",
    org: "VAAS-X",
    name: "Sales",
    role: "Sales inbox",
    vertical: "general",
    stage: "conversion",
    status: "owned",
    channel: "email",
    contact: "sales@vaasx.com",
    url: "mailto:sales@vaasx.com",
    why: "Demo, pilot, paid upgrade, Enterprise.",
  },
  {
    id: "owned-hello",
    org: "VAAS-X",
    name: "Hello",
    role: "General inbox",
    vertical: "general",
    stage: "engagement",
    status: "owned",
    channel: "email",
    contact: "hello@vaasx.com",
    url: "mailto:hello@vaasx.com",
    why: "Product questions and inbound from site.",
  },
  {
    id: "owned-support",
    org: "VAAS-X",
    name: "Support",
    role: "Support inbox",
    vertical: "general",
    stage: "activation",
    status: "owned",
    channel: "email",
    contact: "support@vaasx.com",
    url: "mailto:support@vaasx.com",
    why: "Activation blockers for SDK / MCP users.",
  },

  // Ecosystem / distribution
  {
    id: "eco-mcp-registry",
    org: "MCP Registry",
    name: "Official registry listing",
    role: "Distribution surface",
    vertical: "agents",
    stage: "awareness",
    status: "ecosystem",
    channel: "registry",
    contact: "io.github.VAAS-X/vaasxmcp",
    url: "https://mcp.vaasx.com/mcp",
    why: "Primary awareness channel for Claude / MCP client users.",
  },
  {
    id: "eco-github",
    org: "GitHub",
    name: "VAAS-X/vaas-x",
    role: "Public repo + issues",
    vertical: "agents",
    stage: "awareness",
    status: "ecosystem",
    channel: "github",
    contact: "github.com/VAAS-X/vaas-x",
    url: "https://github.com/VAAS-X/vaas-x",
    why: "Developers discovering SDK examples and filing integration questions.",
  },
  {
    id: "eco-claude-connectors",
    org: "Anthropic Claude",
    name: "Claude.ai Connectors",
    role: "MCP host product",
    vertical: "agents",
    stage: "capture",
    status: "ecosystem",
    channel: "product",
    contact: "Settings → Connectors → https://mcp.vaasx.com/mcp",
    url: "https://claude.ai",
    why: "Where end users add vaasxmcp after seeing the registry listing.",
  },

  // Agent-memory vertical — public orgs / personas
  {
    id: "agents-langchain",
    org: "LangChain",
    name: "Partnerships / DevRel (persona)",
    role: "Head of DevRel / Partnerships",
    vertical: "agents",
    stage: "awareness",
    status: "persona-target",
    channel: "web",
    contact: "langchain.com — partnerships / contact",
    url: "https://www.langchain.com/",
    why: "Agent framework builders need persistent outcome memory beyond session context.",
  },
  {
    id: "agents-llamaindex",
    org: "LlamaIndex",
    name: "Partnerships (persona)",
    role: "Partnerships / Product",
    vertical: "agents",
    stage: "awareness",
    status: "persona-target",
    channel: "web",
    contact: "llamaindex.ai — contact / partners",
    url: "https://www.llamaindex.ai/",
    why: "Memory and retrieval stack audience overlapping agent builders.",
  },
  {
    id: "agents-zep",
    org: "Zep AI",
    name: "Product / partnerships (persona)",
    role: "Founder / Partnerships",
    vertical: "agents",
    stage: "awareness",
    status: "persona-target",
    channel: "linkedin",
    contact: "linkedin.com/company/zep-ai",
    url: "https://www.linkedin.com/company/zep-ai",
    why: "Adjacent agent-memory category — partner, integrate, or win-takeout messaging.",
  },
  {
    id: "agents-cursor-users",
    org: "Cursor / coding-agent users",
    name: "AI engineer persona",
    role: "Staff AI Engineer",
    vertical: "agents",
    stage: "capture",
    status: "persona-target",
    channel: "community",
    contact: "MCP-capable IDE users (Claude Code, Cursor)",
    url: LINKS.mcp,
    why: "High intent for vaasxmcp once they hit session-reset memory pain.",
  },

  // Predictive maintenance
  {
    id: "maint-bytelake",
    org: "byteLAKE",
    name: "Industrial AI contact",
    role: "Sales / Cognitive Services",
    vertical: "maintenance",
    stage: "engagement",
    status: "public-channel",
    channel: "email",
    contact: "welcome@bytelake.com",
    url: "mailto:welcome@bytelake.com",
    why: "Publicly ships CMAPSS predictive-maintenance demos — natural guide/partner audience.",
  },
  {
    id: "maint-exactspace",
    org: "ExactSpace (Pulse)",
    name: "Pulse platform (persona)",
    role: "VP Product / Partnerships",
    vertical: "maintenance",
    stage: "awareness",
    status: "persona-target",
    channel: "web",
    contact: "exactspace.co/pulse — contact form",
    url: "https://exactspace.co/pulse/",
    why: "Industrial PdM platform; Bootstrap + outcome memory is a substrate conversation.",
  },
  {
    id: "maint-gaia",
    org: "GAIA Predictive",
    name: "Partnerships (persona)",
    role: "Founder / Sales",
    vertical: "maintenance",
    stage: "awareness",
    status: "persona-target",
    channel: "web",
    contact: "gaiapredictive.com — contact",
    url: "https://gaiapredictive.com/",
    why: "PLC/SCADA → prescriptive maintenance; fits Connect → Accumulate → Recall story.",
  },
  {
    id: "maint-corsphere",
    org: "CORSphere",
    name: "Defence / marine PdM (persona)",
    role: "BD / Enterprise",
    vertical: "maintenance",
    stage: "expansion",
    status: "persona-target",
    channel: "web",
    contact: "corsphere.com — get started",
    url: "https://www.corsphere.com/",
    why: "Defence/marine anomaly detection — Enterprise / air-gap angle.",
  },

  // Mission / edge
  {
    id: "edge-antmicro",
    org: "Antmicro",
    name: "Edge / robotics engineering",
    role: "Business development",
    vertical: "mission",
    stage: "engagement",
    status: "public-channel",
    channel: "email",
    contact: "contact@antmicro.com",
    url: "mailto:contact@antmicro.com",
    why: "Jetson/robotics/edge product shop — on-device memory (ESP32→cluster) is on-message.",
  },
  {
    id: "edge-espressif",
    org: "Espressif",
    name: "ESP32 ecosystem (persona)",
    role: "Developer relations",
    vertical: "mission",
    stage: "awareness",
    status: "persona-target",
    channel: "web",
    contact: "espressif.com — contact / developers",
    url: "https://www.espressif.com/",
    why: "VAAS-X publishes ESP32-class validation; ecosystem amplification target.",
  },
  {
    id: "edge-nvidia-jetson",
    org: "NVIDIA Jetson ecosystem",
    name: "Robotics / edge AI partners (persona)",
    role: "Ecosystem partner manager",
    vertical: "mission",
    stage: "awareness",
    status: "persona-target",
    channel: "web",
    contact: "developer.nvidia.com/embedded — ecosystem",
    url: "https://developer.nvidia.com/embedded-computing",
    why: "Edge autonomous platforms needing persistent mission memory without cloud round-trip.",
  },

  // Sensitive / regulated
  {
    id: "sens-health-cio",
    org: "Healthcare system (persona)",
    name: "Clinical informatics lead",
    role: "CIO / CMIO / Head of AI",
    vertical: "sensitive",
    stage: "expansion",
    status: "persona-target",
    channel: "outbound",
    contact: "Target via LinkedIn + RFP lists — no personal email stored here",
    url: LINKS.site,
    why: "Encryption-at-rest/transit + Enterprise encrypted-data roadmap conversation.",
  },
  {
    id: "sens-fintech",
    org: "Regulated fintech (persona)",
    name: "Head of AI Platform",
    role: "VP Engineering / CISO co-buy",
    vertical: "sensitive",
    stage: "expansion",
    status: "persona-target",
    channel: "outbound",
    contact: "Enterprise via sales@vaasx.com introductions",
    url: "mailto:sales@vaasx.com",
    why: "Need operational memory without careless data-processor exposure.",
  },
  {
    id: "sens-defence",
    org: "Defence / sovereign IT (persona)",
    name: "Autonomy / C4ISR software lead",
    role: "Technical director",
    vertical: "sensitive",
    stage: "expansion",
    status: "persona-target",
    channel: "outbound",
    contact: "Air-gapped Enterprise path — sales@vaasx.com",
    url: "mailto:sales@vaasx.com",
    why: "On-prem / sovereign deployment matches published Enterprise story.",
  },

  // Warm product motions
  {
    id: "warm-free-keys",
    org: "VAAS-X free-key cohort",
    name: "Existing API key holders",
    role: "Warm leads (owned data)",
    vertical: "general",
    stage: "conversion",
    status: "owned",
    channel: "email",
    contact: "Export from key issuance system → nurture / limit-wall",
    url: LINKS.site,
    why: "Highest-certainty conversion list — already captured on product.",
  },
  {
    id: "warm-mcp-users",
    org: "vaasxmcp connectors",
    name: "OAuth-linked MCP accounts",
    role: "Activated MCP users",
    vertical: "agents",
    stage: "engagement",
    status: "owned",
    channel: "product",
    contact: "Accounts that completed MCP OAuth",
    url: LINKS.mcp,
    why: "Nudge guides → paid tier when episode caps hit.",
  },
];

export const VERTICAL_LABELS = {
  general: "General",
  agents: "Agent memory",
  maintenance: "Predictive maintenance",
  mission: "Mission / edge",
  sensitive: "Sensitive / regulated",
};

export const STAGE_LABELS = Object.fromEntries(FUNNEL.map((s) => [s.id, s.name]));

export const STATUS_LABELS = {
  owned: "Owned",
  ecosystem: "Ecosystem",
  "public-channel": "Public channel",
  "persona-target": "Persona target",
};
